/*
 *  File name:  setup.sql
 *  Function:   to create the initial database schema for the CMPUT 391 project,
 *              Winter Term, 2015
 *  Author:     Prof. Li-Yan Yuan
 */
DROP TABLE family_doctor;
DROP TABLE pacs_images;
DROP TABLE radiology_record;
DROP TABLE users;
DROP TABLE persons;

/*
 *  To store the personal information
 */
CREATE TABLE persons (
   person_id int,
   first_name varchar(24),
   last_name  varchar(24),
   address    varchar(128),
   email      varchar(128),
   phone      char(10),
   PRIMARY KEY(person_id),
   UNIQUE (email)
);

/*
 *  To store the log-in information
 *  Note that a person may have been assigned different user_name(s), depending
 *  on his/her role in the log-in  
 */
CREATE TABLE users (
   user_name varchar(24),
   password  varchar(24),
   class     char(1),
   person_id int,
   date_registered date,
   CHECK (class in ('a','p','d','r')),
   PRIMARY KEY(user_name),
   FOREIGN KEY (person_id) REFERENCES persons
);

/*
 *  to indicate who is whose family doctor.
 */
CREATE TABLE family_doctor (
   doctor_id    int,
   patient_id   int,
   FOREIGN KEY(doctor_id) REFERENCES persons,
   FOREIGN KEY(patient_id) REFERENCES persons,
   PRIMARY KEY(doctor_id,patient_id)
);

/*
 *  to store the radiology records
 */
CREATE TABLE radiology_record (
   record_id   int,
   patient_id  int,
   doctor_id   int,
   radiologist_id int,
   test_type   varchar(24),
   prescribing_date date,
   test_date    date,
   diagnosis    varchar(128),
   description   varchar(1024),
   PRIMARY KEY(record_id),
   FOREIGN KEY(patient_id) REFERENCES persons,
   FOREIGN KEY(doctor_id) REFERENCES  persons,
   FOREIGN KEY(radiologist_id) REFERENCES  persons
);

/*
 *  to store the pacs images
 */
CREATE TABLE pacs_images (
   record_id   int,
   image_id    int,
   thumbnail   blob,
   regular_size blob,
   full_size    blob,
   PRIMARY KEY(record_id,image_id),
   FOREIGN KEY(record_id) REFERENCES radiology_record
);
DROP SEQUENCE person_id;
DROP SEQUENCE record_id;
CREATE SEQUENCE person_id MINVALUE 0 START WITH 0 INCREMENT BY 1;
CREATE SEQUENCE record_id MINVALUE 0 START WITH 0 INCREMENT BY 1;
DROP VIEW information_for_data_analysis;
CREATE VIEW information_for_data_analysis ( FIRST_NAME, LAST_NAME, TEST_TYPE, TEST_DATE ,IMAGE_ID) AS SELECT p.FIRST_NAME, p.LAST_NAME,  r.TEST_TYPE, r.TEST_DATE ,i.IMAGE_ID FROM PERSONS p, RADIOLOGY_RECORD r, PACS_IMAGES i WHERE p.PERSON_ID = r.PATIENT_ID AND i.RECORD_ID = r.RECORD_ID;
Insert into persons values (person_id.nextval, 'Raymond', 'Lieu', 'Edmonton', 'Raymond@hotmail.com', '7800000000');
Insert into persons values (person_id.nextval, 'Liangrui', 'Lu', 'Calgary', 'Liangrui@hotmail.com', '7801111111');
Insert into persons values (person_id.nextval, 'Omar', 'Zioueche', 'Toronto', 'Omar@hotmail.com', '7802222222');
Insert into persons values (person_id.nextval, 'Ichigo', 'Kurosaki', 'Montreal', 'Ichigo@hotmail.com', '7803333333');
Insert into persons values (person_id.nextval, 'Byakuya', 'Kuchiki', 'Quebec', 'Byakuya@hotmail.com', '7804444444');
Insert into persons values (person_id.nextval, 'Urahara', 'Kisuke', 'Goryeo', 'Urahara@hotmail.com', '7805555555');
Insert into persons values (person_id.nextval, 'Hitsuguya', 'Toshiro', 'Gaebong', 'Hitsuguya@hotmail.com', '7806666666');
Insert into persons values (person_id.nextval, 'Renji', 'Abarai', 'Edmonton', 'Renji@hotmail.com', '7807777777');
Insert into persons values (person_id.nextval, 'Aizen', 'Sousuke', 'Calgary', 'Aizen@hotmail.com', '7808888888');
Insert into persons values (person_id.nextval, 'Kenpachi', 'Zaraki', 'Toronto', 'Kenpachi@hotmail.com', '7800000000');
Insert into persons values (person_id.nextval, 'Naruto', 'Uzumaki', 'Montreal', 'Naruto@hotmail.com', '7801111111');
Insert into persons values (person_id.nextval, 'Sasuke', 'Uchiha', 'Quebec', 'Sasuke@hotmail.com', '7802222222');
Insert into persons values (person_id.nextval, 'Itachi', 'Uchiha', 'Goryeo', 'Itachi@hotmail.com', '7803333333');
Insert into persons values (person_id.nextval, 'Madara', 'Uchiha', 'Gaebong', 'Madara@hotmail.com', '7804444444');
Insert into persons values (person_id.nextval, 'Kakashi', 'Hatake', 'Edmonton', 'Kakashi@hotmail.com', '7805555555');
Insert into persons values (person_id.nextval, 'Hinata', 'Hyuga', 'Calgary', 'Hinata@hotmail.com', '7806666666');
Insert into persons values (person_id.nextval, 'Oga', 'Tatsumi', 'Toronto', 'Oga@hotmail.com', '7807777777');
Insert into persons values (person_id.nextval, 'Aoi', 'Kuneida', 'Montreal', 'Aoi@hotmail.com', '7808888888');
Insert into persons values (person_id.nextval, 'Tatsuya', 'Shiba', 'Quebec', 'Tatsuya@hotmail.com', '7800000000');
Insert into persons values (person_id.nextval, 'Miyuki', 'Shiba', 'Goryeo', 'Miyuki@hotmail.com', '7801111111');
Insert into persons values (person_id.nextval, 'Moroha', 'Haimura', 'Gaebong', 'Moroha@hotmail.com', '7802222222');
Insert into users values ('admin', 'admin', 'a', 2, '04-Apr-2015');
Insert into users values ('a_RaymondLieu', 'pwd', 'a', 0, '07-Apr-2015');
Insert into users values ('d_RaymondLieu', 'pwd', 'd', 0, '08-Apr-2015');
Insert into users values ('r_RaymondLieu', 'pwd', 'r', 0, '09-Apr-2015');
Insert into users values ('p_RaymondLieu', 'pwd', 'p', 0, '04-Apr-2015');
Insert into users values ('p_LiangruiLu', 'pwd', 'p', 1, '05-Apr-2015');
Insert into users values ('d_OmarZioueche', 'pwd', 'd', 2, '20-Apr-2015');
Insert into users values ('p_OmarZioueche', 'pwd', 'p', 2, '06-Apr-2015');
Insert into users values ('a_IchigoKurosaki', 'pwd', 'a', 3, '28-Apr-2015');
Insert into users values ('p_IchigoKurosaki', 'pwd', 'p', 3, '07-Apr-2015');
Insert into users values ('d_ByakuyaKuchiki', 'pwd', 'd', 4, '10-May-2015');
Insert into users values ('p_ByakuyaKuchiki', 'pwd', 'p', 4, '08-Apr-2015');
Insert into users values ('r_UraharaKisuke', 'pwd', 'r', 5, '03-Jun-2015');
Insert into users values ('p_UraharaKisuke', 'pwd', 'p', 5, '09-Apr-2015');
Insert into users values ('a_HitsuguyaToshiro', 'pwd', 'a', 6, '06-Jun-2015');
Insert into users values ('d_HitsuguyaToshiro', 'pwd', 'd', 6, '07-Jun-2015');
Insert into users values ('p_HitsuguyaToshiro', 'pwd', 'p', 6, '10-Apr-2015');
Insert into users values ('p_RenjiAbarai', 'pwd', 'p', 7, '11-Apr-2015');
Insert into users values ('d_AizenSousuke', 'pwd', 'd', 8, '13-Jul-2015');
Insert into users values ('p_AizenSousuke', 'pwd', 'p', 8, '12-Apr-2015');
Insert into users values ('a_KenpachiZaraki', 'pwd', 'a', 9, '02-Aug-2015');
Insert into users values ('p_KenpachiZaraki', 'pwd', 'p', 9, '13-Apr-2015');
Insert into users values ('d_NarutoUzumaki', 'pwd', 'd', 10, '26-Aug-2015');
Insert into users values ('r_NarutoUzumaki', 'pwd', 'r', 10, '16-Sep-2015');
Insert into users values ('p_NarutoUzumaki', 'pwd', 'p', 10, '14-Apr-2015');
Insert into users values ('p_SasukeUchiha', 'pwd', 'p', 11, '15-Apr-2015');
Insert into users values ('a_ItachiUchiha', 'pwd', 'a', 12, '16-Oct-2015');
Insert into users values ('d_ItachiUchiha', 'pwd', 'd', 12, '17-Oct-2015');
Insert into users values ('p_ItachiUchiha', 'pwd', 'p', 12, '16-Apr-2015');
Insert into users values ('p_MadaraUchiha', 'pwd', 'p', 13, '17-Apr-2015');
Insert into users values ('d_KakashiHatake', 'pwd', 'd', 14, '16-Dec-2015');
Insert into users values ('p_KakashiHatake', 'pwd', 'p', 14, '18-Apr-2015');
Insert into users values ('a_HinataHyuga', 'pwd', 'a', 15, '17-Jan-2016');
Insert into users values ('r_HinataHyuga', 'pwd', 'r', 15, '18-Feb-2016');
Insert into users values ('p_HinataHyuga', 'pwd', 'p', 15, '19-Apr-2015');
Insert into users values ('d_OgaTatsumi', 'pwd', 'd', 16, '22-Feb-2016');
Insert into users values ('p_OgaTatsumi', 'pwd', 'p', 16, '20-Apr-2015');
Insert into users values ('p_AoiKuneida', 'pwd', 'p', 17, '21-Apr-2015');
Insert into users values ('a_TatsuyaShiba', 'pwd', 'a', 18, '07-May-2016');
Insert into users values ('d_TatsuyaShiba', 'pwd', 'd', 18, '08-May-2016');
Insert into users values ('p_TatsuyaShiba', 'pwd', 'p', 18, '22-Apr-2015');
Insert into users values ('p_MiyukiShiba', 'pwd', 'p', 19, '23-Apr-2015');
Insert into users values ('d_MorohaHaimura', 'pwd', 'd', 20, '31-Jul-2016');
Insert into users values ('r_MorohaHaimura', 'pwd', 'r', 20, '10-Sep-2016');
Insert into users values ('p_MorohaHaimura', 'pwd', 'p', 20, '24-Apr-2015');
Insert into family_doctor values (2, 0);
Insert into family_doctor values (4, 0);
Insert into family_doctor values (6, 0);
Insert into family_doctor values (8, 0);
Insert into family_doctor values (10, 0);
Insert into family_doctor values (12, 0);
Insert into family_doctor values (14, 0);
Insert into family_doctor values (16, 0);
Insert into family_doctor values (18, 0);
Insert into family_doctor values (20, 0);
Insert into family_doctor values (0, 1);
Insert into family_doctor values (2, 1);
Insert into family_doctor values (4, 1);
Insert into family_doctor values (6, 1);
Insert into family_doctor values (8, 1);
Insert into family_doctor values (10, 1);
Insert into family_doctor values (12, 1);
Insert into family_doctor values (14, 1);
Insert into family_doctor values (16, 1);
Insert into family_doctor values (18, 1);
Insert into family_doctor values (20, 1);
Insert into family_doctor values (0, 2);
Insert into family_doctor values (4, 2);
Insert into family_doctor values (6, 2);
Insert into family_doctor values (8, 2);
Insert into family_doctor values (10, 2);
Insert into family_doctor values (12, 2);
Insert into family_doctor values (14, 2);
Insert into family_doctor values (16, 2);
Insert into family_doctor values (18, 2);
Insert into family_doctor values (20, 2);
Insert into family_doctor values (0, 3);
Insert into family_doctor values (2, 3);
Insert into family_doctor values (4, 3);
Insert into family_doctor values (6, 3);
Insert into family_doctor values (8, 3);
Insert into family_doctor values (10, 3);
Insert into family_doctor values (12, 3);
Insert into family_doctor values (14, 3);
Insert into family_doctor values (16, 3);
Insert into family_doctor values (18, 3);
Insert into family_doctor values (20, 3);
Insert into family_doctor values (0, 4);
Insert into family_doctor values (2, 4);
Insert into family_doctor values (6, 4);
Insert into family_doctor values (8, 4);
Insert into family_doctor values (10, 4);
Insert into family_doctor values (12, 4);
Insert into family_doctor values (14, 4);
Insert into family_doctor values (16, 4);
Insert into family_doctor values (18, 4);
Insert into family_doctor values (20, 4);
Insert into family_doctor values (0, 5);
Insert into family_doctor values (2, 5);
Insert into family_doctor values (4, 5);
Insert into family_doctor values (6, 5);
Insert into family_doctor values (8, 5);
Insert into family_doctor values (10, 5);
Insert into family_doctor values (12, 5);
Insert into family_doctor values (14, 5);
Insert into family_doctor values (16, 5);
Insert into family_doctor values (18, 5);
Insert into family_doctor values (20, 5);
Insert into family_doctor values (0, 6);
Insert into family_doctor values (2, 6);
Insert into family_doctor values (4, 6);
Insert into family_doctor values (8, 6);
Insert into family_doctor values (10, 6);
Insert into family_doctor values (12, 6);
Insert into family_doctor values (14, 6);
Insert into family_doctor values (16, 6);
Insert into family_doctor values (18, 6);
Insert into family_doctor values (20, 6);
Insert into family_doctor values (0, 7);
Insert into family_doctor values (2, 7);
Insert into family_doctor values (4, 7);
Insert into family_doctor values (6, 7);
Insert into family_doctor values (8, 7);
Insert into family_doctor values (10, 7);
Insert into family_doctor values (12, 7);
Insert into family_doctor values (14, 7);
Insert into family_doctor values (16, 7);
Insert into family_doctor values (18, 7);
Insert into family_doctor values (20, 7);
Insert into family_doctor values (0, 8);
Insert into family_doctor values (2, 8);
Insert into family_doctor values (4, 8);
Insert into family_doctor values (6, 8);
Insert into family_doctor values (10, 8);
Insert into family_doctor values (12, 8);
Insert into family_doctor values (14, 8);
Insert into family_doctor values (16, 8);
Insert into family_doctor values (18, 8);
Insert into family_doctor values (20, 8);
Insert into family_doctor values (0, 9);
Insert into family_doctor values (2, 9);
Insert into family_doctor values (4, 9);
Insert into family_doctor values (6, 9);
Insert into family_doctor values (8, 9);
Insert into family_doctor values (10, 9);
Insert into family_doctor values (12, 9);
Insert into family_doctor values (14, 9);
Insert into family_doctor values (16, 9);
Insert into family_doctor values (18, 9);
Insert into family_doctor values (20, 9);
Insert into family_doctor values (0, 10);
Insert into family_doctor values (2, 10);
Insert into family_doctor values (4, 10);
Insert into family_doctor values (6, 10);
Insert into family_doctor values (8, 10);
Insert into family_doctor values (12, 10);
Insert into family_doctor values (14, 10);
Insert into family_doctor values (16, 10);
Insert into family_doctor values (18, 10);
Insert into family_doctor values (20, 10);
Insert into family_doctor values (0, 11);
Insert into family_doctor values (2, 11);
Insert into family_doctor values (4, 11);
Insert into family_doctor values (6, 11);
Insert into family_doctor values (8, 11);
Insert into family_doctor values (10, 11);
Insert into family_doctor values (12, 11);
Insert into family_doctor values (14, 11);
Insert into family_doctor values (16, 11);
Insert into family_doctor values (18, 11);
Insert into family_doctor values (20, 11);
Insert into family_doctor values (0, 12);
Insert into family_doctor values (2, 12);
Insert into family_doctor values (4, 12);
Insert into family_doctor values (6, 12);
Insert into family_doctor values (8, 12);
Insert into family_doctor values (10, 12);
Insert into family_doctor values (14, 12);
Insert into family_doctor values (16, 12);
Insert into family_doctor values (18, 12);
Insert into family_doctor values (20, 12);
Insert into family_doctor values (0, 13);
Insert into family_doctor values (2, 13);
Insert into family_doctor values (4, 13);
Insert into family_doctor values (6, 13);
Insert into family_doctor values (8, 13);
Insert into family_doctor values (10, 13);
Insert into family_doctor values (12, 13);
Insert into family_doctor values (14, 13);
Insert into family_doctor values (16, 13);
Insert into family_doctor values (18, 13);
Insert into family_doctor values (20, 13);
Insert into family_doctor values (0, 14);
Insert into family_doctor values (2, 14);
Insert into family_doctor values (4, 14);
Insert into family_doctor values (6, 14);
Insert into family_doctor values (8, 14);
Insert into family_doctor values (10, 14);
Insert into family_doctor values (12, 14);
Insert into family_doctor values (16, 14);
Insert into family_doctor values (18, 14);
Insert into family_doctor values (20, 14);
Insert into family_doctor values (0, 15);
Insert into family_doctor values (2, 15);
Insert into family_doctor values (4, 15);
Insert into family_doctor values (6, 15);
Insert into family_doctor values (8, 15);
Insert into family_doctor values (10, 15);
Insert into family_doctor values (12, 15);
Insert into family_doctor values (14, 15);
Insert into family_doctor values (16, 15);
Insert into family_doctor values (18, 15);
Insert into family_doctor values (20, 15);
Insert into family_doctor values (0, 16);
Insert into family_doctor values (2, 16);
Insert into family_doctor values (4, 16);
Insert into family_doctor values (6, 16);
Insert into family_doctor values (8, 16);
Insert into family_doctor values (10, 16);
Insert into family_doctor values (12, 16);
Insert into family_doctor values (14, 16);
Insert into family_doctor values (18, 16);
Insert into family_doctor values (20, 16);
Insert into family_doctor values (0, 17);
Insert into family_doctor values (2, 17);
Insert into family_doctor values (4, 17);
Insert into family_doctor values (6, 17);
Insert into family_doctor values (8, 17);
Insert into family_doctor values (10, 17);
Insert into family_doctor values (12, 17);
Insert into family_doctor values (14, 17);
Insert into family_doctor values (16, 17);
Insert into family_doctor values (18, 17);
Insert into family_doctor values (20, 17);
Insert into family_doctor values (0, 18);
Insert into family_doctor values (2, 18);
Insert into family_doctor values (4, 18);
Insert into family_doctor values (6, 18);
Insert into family_doctor values (8, 18);
Insert into family_doctor values (10, 18);
Insert into family_doctor values (12, 18);
Insert into family_doctor values (14, 18);
Insert into family_doctor values (16, 18);
Insert into family_doctor values (20, 18);
Insert into family_doctor values (0, 19);
Insert into family_doctor values (2, 19);
Insert into family_doctor values (4, 19);
Insert into family_doctor values (6, 19);
Insert into family_doctor values (8, 19);
Insert into family_doctor values (10, 19);
Insert into family_doctor values (12, 19);
Insert into family_doctor values (14, 19);
Insert into family_doctor values (16, 19);
Insert into family_doctor values (18, 19);
Insert into family_doctor values (20, 19);
Insert into family_doctor values (0, 20);
Insert into family_doctor values (2, 20);
Insert into family_doctor values (4, 20);
Insert into family_doctor values (6, 20);
Insert into family_doctor values (8, 20);
Insert into family_doctor values (10, 20);
Insert into family_doctor values (12, 20);
Insert into family_doctor values (14, 20);
Insert into family_doctor values (16, 20);
Insert into family_doctor values (18, 20);
Insert into radiology_record values (record_id.NEXTVAL, 1, 2, 0, 'BLOOD', '06-Apr-2015', '15-Feb-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 1, 4, 0, 'MRI', '08-Apr-2015', '17-Feb-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 1, 6, 0, 'X-RAY', '10-Apr-2015', '19-Feb-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 1, 8, 0, 'DNA', '12-Apr-2015', '21-Feb-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 1, 10, 0, 'CT', '14-Apr-2015', '23-Feb-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 1, 12, 0, 'BLOOD', '16-Apr-2015', '25-Feb-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 1, 14, 0, 'MRI', '18-Apr-2015', '27-Feb-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 1, 16, 0, 'X-RAY', '20-Apr-2015', '29-Feb-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 1, 18, 0, 'DNA', '22-Apr-2015', '02-Mar-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 1, 20, 0, 'CT', '24-Apr-2015', '04-Mar-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 2, 4, 0, 'BLOOD', '20-Apr-2015', '29-Feb-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 2, 6, 0, 'MRI', '28-Apr-2015', '08-Mar-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 2, 8, 0, 'X-RAY', '06-May-2015', '16-Mar-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 2, 10, 0, 'DNA', '14-May-2015', '24-Mar-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 2, 12, 0, 'CT', '22-May-2015', '01-Apr-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 2, 14, 0, 'BLOOD', '30-May-2015', '09-Apr-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 2, 16, 0, 'MRI', '07-Jun-2015', '17-Apr-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 2, 18, 0, 'X-RAY', '15-Jun-2015', '25-Apr-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 2, 20, 0, 'DNA', '23-Jun-2015', '03-May-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 3, 2, 0, 'CT', '22-Apr-2015', '02-Mar-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 3, 4, 0, 'BLOOD', '10-May-2015', '20-Mar-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 3, 6, 0, 'MRI', '28-May-2015', '07-Apr-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 3, 8, 0, 'X-RAY', '15-Jun-2015', '25-Apr-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 3, 10, 0, 'DNA', '03-Jul-2015', '13-May-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 3, 12, 0, 'CT', '21-Jul-2015', '31-May-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 3, 14, 0, 'BLOOD', '08-Aug-2015', '18-Jun-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 3, 16, 0, 'MRI', '26-Aug-2015', '06-Jul-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 3, 18, 0, 'X-RAY', '13-Sep-2015', '24-Jul-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 3, 20, 0, 'DNA', '01-Oct-2015', '11-Aug-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 4, 2, 0, 'BLOOD', '06-May-2015', '16-Mar-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 4, 6, 0, 'X-RAY', '09-Jul-2015', '19-May-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 4, 8, 0, 'DNA', '10-Aug-2015', '20-Jun-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 4, 10, 0, 'CT', '11-Sep-2015', '22-Jul-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 4, 12, 0, 'BLOOD', '13-Oct-2015', '23-Aug-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 4, 14, 0, 'MRI', '14-Nov-2015', '24-Sep-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 4, 16, 0, 'X-RAY', '16-Dec-2015', '26-Oct-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 4, 18, 0, 'DNA', '17-Jan-2016', '27-Nov-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 4, 20, 0, 'CT', '24-Apr-2015', '29-Dec-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 5, 2, 0, 'X-RAY', '24-May-2015', '03-Apr-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 5, 4, 0, 'DNA', '13-Jul-2015', '23-May-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 5, 6, 0, 'CT', '01-Sep-2015', '12-Jul-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 5, 8, 0, 'BLOOD', '21-Oct-2015', '31-Aug-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 5, 10, 0, 'MRI', '10-Dec-2015', '20-Oct-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 5, 12, 0, 'X-RAY', '04-Apr-2015', '09-Dec-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 5, 14, 0, 'DNA', '24-May-2015', '28-Jan-2017', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 5, 16, 0, 'CT', '13-Jul-2015', '19-Mar-2017', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 5, 18, 0, 'BLOOD', '01-Sep-2015', '08-May-2017', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 5, 20, 0, 'MRI', '21-Oct-2015', '27-Jun-2017', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 6, 2, 0, 'BLOOD', '15-Jun-2015', '25-Apr-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 6, 4, 0, 'MRI', '26-Aug-2015', '06-Jul-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 6, 8, 0, 'DNA', '17-Jan-2016', '27-Nov-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 6, 10, 0, 'CT', '03-Jun-2015', '07-Feb-2017', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 6, 12, 0, 'BLOOD', '14-Aug-2015', '20-Apr-2017', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 6, 14, 0, 'MRI', '25-Oct-2015', '01-Jul-2017', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 6, 16, 0, 'X-RAY', '05-Jan-2016', '11-Sep-2017', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 6, 18, 0, 'DNA', '22-May-2015', '22-Nov-2017', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 6, 20, 0, 'CT', '02-Aug-2015', '02-Feb-2018', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 7, 2, 0, 'CT', '11-Jul-2015', '21-May-2016', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 7, 4, 0, 'BLOOD', '17-Oct-2015', '27-Aug-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 7, 6, 0, 'MRI', '23-Jan-2016', '03-Dec-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 7, 8, 0, 'X-RAY', '05-Jul-2015', '11-Mar-2017', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 7, 10, 0, 'DNA', '11-Oct-2015', '17-Jun-2017', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 7, 12, 0, 'CT', '17-Jan-2016', '23-Sep-2017', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 7, 14, 0, 'BLOOD', '29-Jun-2015', '30-Dec-2017', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 7, 16, 0, 'MRI', '05-Oct-2015', '07-Apr-2018', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 7, 18, 0, 'X-RAY', '11-Jan-2016', '14-Jul-2018', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 7, 20, 0, 'DNA', '23-Jun-2015', '20-Oct-2018', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 8, 2, 0, 'CT', '10-Aug-2015', '20-Jun-2016', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 8, 4, 0, 'BLOOD', '16-Dec-2015', '26-Oct-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 8, 6, 0, 'MRI', '27-Jun-2015', '03-Mar-2017', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 8, 10, 0, 'DNA', '14-May-2015', '14-Nov-2017', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 8, 12, 0, 'CT', '19-Sep-2015', '22-Mar-2018', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 8, 14, 0, 'BLOOD', '25-Jan-2016', '28-Jul-2018', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 8, 16, 0, 'MRI', '06-Aug-2015', '03-Dec-2018', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 8, 18, 0, 'X-RAY', '12-Dec-2015', '10-Apr-2019', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 8, 20, 0, 'DNA', '23-Jun-2015', '16-Aug-2019', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 9, 2, 0, 'BLOOD', '13-Sep-2015', '24-Jul-2016', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 9, 4, 0, 'MRI', '28-Apr-2015', '02-Jan-2017', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 9, 6, 0, 'X-RAY', '07-Oct-2015', '13-Jun-2017', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 9, 8, 0, 'DNA', '22-May-2015', '22-Nov-2017', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 9, 10, 0, 'CT', '31-Oct-2015', '03-May-2018', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 9, 12, 0, 'BLOOD', '15-Jun-2015', '12-Oct-2018', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 9, 14, 0, 'MRI', '24-Nov-2015', '23-Mar-2019', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 9, 16, 0, 'X-RAY', '09-Jul-2015', '01-Sep-2019', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 9, 18, 0, 'DNA', '18-Dec-2015', '10-Feb-2020', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 9, 20, 0, 'CT', '02-Aug-2015', '21-Jul-2020', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 10, 2, 0, 'X-RAY', '21-Oct-2015', '31-Aug-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 10, 4, 0, 'DNA', '13-Jul-2015', '19-Mar-2017', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 10, 6, 0, 'CT', '04-Apr-2015', '05-Oct-2017', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 10, 8, 0, 'BLOOD', '21-Oct-2015', '23-Apr-2018', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 10, 12, 0, 'X-RAY', '04-Apr-2015', '28-May-2019', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 10, 14, 0, 'DNA', '21-Oct-2015', '14-Dec-2019', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 10, 16, 0, 'CT', '13-Jul-2015', '01-Jul-2020', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 10, 18, 0, 'BLOOD', '04-Apr-2015', '17-Jan-2021', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 10, 20, 0, 'MRI', '21-Oct-2015', '05-Aug-2021', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 11, 2, 0, 'BLOOD', '02-Dec-2015', '12-Oct-2016', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 11, 4, 0, 'MRI', '05-Oct-2015', '11-Jun-2017', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 11, 6, 0, 'X-RAY', '08-Aug-2015', '08-Feb-2018', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 11, 8, 0, 'DNA', '11-Jun-2015', '08-Oct-2018', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 11, 10, 0, 'CT', '14-Apr-2015', '07-Jun-2019', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 11, 12, 0, 'BLOOD', '12-Dec-2015', '04-Feb-2020', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 11, 14, 0, 'MRI', '15-Oct-2015', '03-Oct-2020', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 11, 16, 0, 'X-RAY', '18-Aug-2015', '02-Jun-2021', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 11, 18, 0, 'DNA', '21-Jun-2015', '30-Jan-2022', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 11, 20, 0, 'CT', '24-Apr-2015', '29-Sep-2022', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 12, 2, 0, 'CT', '17-Jan-2016', '27-Nov-2016', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 12, 4, 0, 'BLOOD', '05-Jan-2016', '11-Sep-2017', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 12, 6, 0, 'MRI', '24-Dec-2015', '26-Jun-2018', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 12, 8, 0, 'X-RAY', '12-Dec-2015', '10-Apr-2019', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 12, 10, 0, 'DNA', '30-Nov-2015', '23-Jan-2020', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 12, 14, 0, 'BLOOD', '06-Nov-2015', '21-Aug-2021', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 12, 16, 0, 'MRI', '25-Oct-2015', '05-Jun-2022', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 12, 18, 0, 'X-RAY', '13-Oct-2015', '20-Mar-2023', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 12, 20, 0, 'DNA', '01-Oct-2015', '02-Jan-2024', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 13, 2, 0, 'CT', '12-May-2015', '16-Jan-2017', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 13, 4, 0, 'BLOOD', '19-Jun-2015', '20-Dec-2017', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 13, 6, 0, 'MRI', '27-Jul-2015', '23-Nov-2018', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 13, 8, 0, 'X-RAY', '03-Sep-2015', '27-Oct-2019', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 13, 10, 0, 'DNA', '11-Oct-2015', '29-Sep-2020', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 13, 12, 0, 'CT', '18-Nov-2015', '02-Sep-2021', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 13, 14, 0, 'BLOOD', '26-Dec-2015', '06-Aug-2022', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 13, 16, 0, 'MRI', '08-Apr-2015', '10-Jul-2023', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 13, 18, 0, 'X-RAY', '16-May-2015', '12-Jun-2024', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 13, 20, 0, 'DNA', '23-Jun-2015', '16-May-2025', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 14, 2, 0, 'BLOOD', '05-Jul-2015', '11-Mar-2017', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 14, 4, 0, 'MRI', '05-Oct-2015', '07-Apr-2018', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 14, 6, 0, 'X-RAY', '05-Jan-2016', '04-May-2019', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 14, 8, 0, 'DNA', '11-Jun-2015', '30-May-2020', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 14, 10, 0, 'CT', '11-Sep-2015', '26-Jun-2021', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 14, 12, 0, 'BLOOD', '12-Dec-2015', '23-Jul-2022', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 14, 16, 0, 'X-RAY', '18-Aug-2015', '14-Sep-2024', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 14, 18, 0, 'DNA', '18-Nov-2015', '11-Oct-2025', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 14, 20, 0, 'CT', '24-Apr-2015', '07-Nov-2026', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 15, 2, 0, 'X-RAY', '01-Sep-2015', '08-May-2017', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 15, 4, 0, 'DNA', '04-Apr-2015', '01-Aug-2018', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 15, 6, 0, 'CT', '01-Sep-2015', '25-Oct-2019', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 15, 8, 0, 'BLOOD', '04-Apr-2015', '17-Jan-2021', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 15, 10, 0, 'MRI', '01-Sep-2015', '12-Apr-2022', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 15, 12, 0, 'X-RAY', '04-Apr-2015', '06-Jul-2023', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 15, 14, 0, 'DNA', '01-Sep-2015', '28-Sep-2024', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 15, 16, 0, 'CT', '04-Apr-2015', '22-Dec-2025', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 15, 18, 0, 'BLOOD', '01-Sep-2015', '17-Mar-2027', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 15, 20, 0, 'MRI', '04-Apr-2015', '09-Jun-2028', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 16, 2, 0, 'BLOOD', '02-Nov-2015', '09-Jul-2017', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 16, 4, 0, 'MRI', '06-Aug-2015', '03-Dec-2018', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 16, 6, 0, 'X-RAY', '10-May-2015', '28-Apr-2020', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 16, 8, 0, 'DNA', '08-Dec-2015', '22-Sep-2021', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 16, 10, 0, 'CT', '11-Sep-2015', '16-Feb-2023', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 16, 12, 0, 'BLOOD', '15-Jun-2015', '12-Jul-2024', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 16, 14, 0, 'MRI', '13-Jan-2016', '06-Dec-2025', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 16, 18, 0, 'DNA', '21-Jul-2015', '25-Sep-2028', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 16, 20, 0, 'CT', '24-Apr-2015', '19-Feb-2030', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 17, 2, 0, 'CT', '07-Jan-2016', '13-Sep-2017', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 17, 4, 0, 'BLOOD', '16-Dec-2015', '14-Apr-2019', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 17, 6, 0, 'MRI', '24-Nov-2015', '12-Nov-2020', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 17, 8, 0, 'X-RAY', '02-Nov-2015', '13-Jun-2022', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 17, 10, 0, 'DNA', '11-Oct-2015', '12-Jan-2024', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 17, 12, 0, 'CT', '19-Sep-2015', '12-Aug-2025', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 17, 14, 0, 'BLOOD', '28-Aug-2015', '13-Mar-2027', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 17, 16, 0, 'MRI', '06-Aug-2015', '11-Oct-2028', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 17, 18, 0, 'X-RAY', '15-Jul-2015', '12-May-2030', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 17, 20, 0, 'DNA', '23-Jun-2015', '11-Dec-2031', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 18, 2, 0, 'CT', '22-May-2015', '22-Nov-2017', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 18, 4, 0, 'BLOOD', '09-Jul-2015', '01-Sep-2019', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 18, 6, 0, 'MRI', '26-Aug-2015', '10-Jun-2021', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 18, 8, 0, 'X-RAY', '13-Oct-2015', '20-Mar-2023', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 18, 10, 0, 'DNA', '30-Nov-2015', '27-Dec-2024', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 18, 12, 0, 'CT', '17-Jan-2016', '06-Oct-2026', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 18, 14, 0, 'BLOOD', '10-May-2015', '15-Jul-2028', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 18, 16, 0, 'MRI', '27-Jun-2015', '24-Apr-2030', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 18, 20, 0, 'DNA', '01-Oct-2015', '10-Nov-2033', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 19, 2, 0, 'BLOOD', '04-Aug-2015', '04-Feb-2018', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 19, 4, 0, 'MRI', '04-Dec-2015', '27-Jan-2020', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 19, 6, 0, 'X-RAY', '09-Jun-2015', '18-Jan-2022', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 19, 8, 0, 'DNA', '09-Oct-2015', '10-Jan-2024', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 19, 10, 0, 'CT', '14-Apr-2015', '01-Jan-2026', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 19, 12, 0, 'BLOOD', '14-Aug-2015', '24-Dec-2027', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 19, 14, 0, 'MRI', '14-Dec-2015', '15-Dec-2029', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 19, 16, 0, 'X-RAY', '19-Jun-2015', '07-Dec-2031', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 19, 18, 0, 'DNA', '19-Oct-2015', '28-Nov-2033', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 19, 20, 0, 'CT', '24-Apr-2015', '20-Nov-2035', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 20, 2, 0, 'X-RAY', '21-Oct-2015', '23-Apr-2018', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 20, 4, 0, 'DNA', '13-Jul-2015', '01-Jul-2020', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into radiology_record values (record_id.NEXTVAL, 20, 6, 0, 'CT', '04-Apr-2015', '09-Sep-2022', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 20, 8, 0, 'BLOOD', '21-Oct-2015', '17-Nov-2024', 'ALIVE', 'Cannot believe the doctor actually did it');
Insert into radiology_record values (record_id.NEXTVAL, 20, 10, 0, 'MRI', '13-Jul-2015', '26-Jan-2027', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 20, 12, 0, 'X-RAY', '04-Apr-2015', '05-Apr-2029', 'BURNED', 'Darn that Groudon and its fire blast');
Insert into radiology_record values (record_id.NEXTVAL, 20, 14, 0, 'DNA', '21-Oct-2015', '14-Jun-2031', 'DEAD', 'Doctor messed up');
Insert into radiology_record values (record_id.NEXTVAL, 20, 16, 0, 'CT', '13-Jul-2015', '22-Aug-2033', 'COMATOSE', 'Weird...');
Insert into radiology_record values (record_id.NEXTVAL, 20, 18, 0, 'BLOOD', '04-Apr-2015', '31-Oct-2035', 'PARALYZED', 'Darn that Pikachu and its thunder bolt');
Insert into pacs_images values (0, 0, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 10, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 20, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 30, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 40, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 50, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 60, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 70, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 80, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 90, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 100, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 110, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 120, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 130, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 140, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 150, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 160, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 170, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 180, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (0, 190, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 200, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 210, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 220, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 230, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 240, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 250, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 260, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 270, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 280, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 290, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 300, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 310, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 320, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 330, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 340, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 350, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 360, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (1, 370, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 380, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 390, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 400, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 410, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 420, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 430, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 440, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 450, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 460, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 470, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 480, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 490, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 500, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 510, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 520, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 530, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 540, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 550, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 560, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (2, 570, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 580, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 590, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 600, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 610, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 620, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 630, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 640, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 650, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 660, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 670, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 680, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 690, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 700, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 710, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 720, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 730, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 740, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (3, 750, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 760, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 770, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 780, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 790, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 800, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 810, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 820, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 830, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 840, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 850, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 860, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 870, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 880, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 890, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 900, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 910, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 920, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 930, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 940, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (4, 950, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 960, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 970, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 980, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 990, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1000, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1010, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1020, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1030, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1040, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1050, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1060, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1070, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1080, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1090, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1100, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1110, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1120, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (5, 1130, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1140, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1150, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1160, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1170, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1180, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1190, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1200, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1210, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1220, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1230, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1240, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1250, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1260, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1270, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1280, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1290, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1300, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1310, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1320, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (6, 1330, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1340, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1350, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1360, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1370, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1380, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1390, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1400, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1410, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1420, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1430, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1440, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1450, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1460, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1470, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1480, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1490, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1500, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (7, 1510, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1520, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1530, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1540, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1550, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1560, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1570, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1580, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1590, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1600, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1610, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1620, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1630, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1640, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1650, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1660, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1670, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1680, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1690, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1700, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (8, 1710, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1720, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1730, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1740, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1750, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1760, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1770, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1780, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1790, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1800, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1810, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1820, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1830, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1840, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1850, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1860, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1870, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1880, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (9, 1890, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1900, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1910, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1920, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1930, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1940, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1950, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1960, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1970, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1980, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 1990, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2000, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2010, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2020, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2030, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2040, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2050, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2060, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2070, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2080, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (10, 2090, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2100, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2110, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2120, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2130, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2140, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2150, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2160, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2170, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2180, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2190, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2200, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2210, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2220, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2230, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2240, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2250, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2260, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (11, 2270, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2280, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2290, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2300, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2310, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2320, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2330, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2340, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2350, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2360, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2370, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2380, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2390, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2400, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2410, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2420, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2430, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2440, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2450, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2460, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (12, 2470, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2480, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2490, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2500, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2510, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2520, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2530, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2540, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2550, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2560, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2570, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2580, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2590, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2600, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2610, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2620, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2630, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2640, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (13, 2650, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2660, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2670, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2680, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2690, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2700, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2710, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2720, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2730, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2740, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2750, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2760, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2770, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2780, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2790, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2800, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2810, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2820, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2830, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2840, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (14, 2850, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2860, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2870, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2880, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2890, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2900, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2910, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2920, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2930, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2940, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2950, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2960, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2970, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2980, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 2990, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 3000, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 3010, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 3020, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (15, 3030, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3040, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3050, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3060, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3070, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3080, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3090, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3100, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3110, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3120, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3130, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3140, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3150, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3160, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3170, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3180, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3190, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3200, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3210, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3220, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (16, 3230, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3240, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3250, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3260, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3270, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3280, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3290, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3300, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3310, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3320, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3330, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3340, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3350, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3360, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3370, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3380, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3390, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3400, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (17, 3410, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3420, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3430, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3440, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3450, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3460, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3470, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3480, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3490, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3500, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3510, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3520, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3530, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3540, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3550, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3560, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3570, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3580, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3590, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3600, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (18, 3610, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3620, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3630, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3640, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3650, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3660, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3670, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3680, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3690, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3700, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3710, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3720, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3730, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3740, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3750, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3760, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3770, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3780, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Insert into pacs_images values (19, 3790, RAWTOHEX('Test Thumbnail'), RAWTOHEX('Test Regular Size'), RAWTOHEX('Test Full Size'));
Create index indexa on persons(first_name) indextype is ctxsys.context;
Create index indexb on persons(last_name) indextype is ctxsys.context;
Create index indexc on radiology_record(diagnosis) indextype is ctxsys.context;
Create index indexd on radiology_record(description) indextype is ctxsys.context;
Commit;